services:
  budget_tracker_analytics:
    build: .
    container_name: budget_tracker_analytics
    # This is the missing piece! 
    # Maps your computer's port 10000 to the container's 10000
    ports:
      - "10000:10000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
      # Forces Python to flush logs to the console immediately
      - PYTHONUNBUFFERED=1