services:
  budget_tracker_analytics:
    build: .
    container_name: budget_tracker_analytics
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      GOOGLE_SHEET_ID: ${GOOGLE_SHEET_ID}